// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUEr1vknC5jou9fBsXEbxpfCHS6hQx3Qo',
    appId: '1:7485850405:web:6fca3131ce2642a827d0cc',
    messagingSenderId: '7485850405',
    projectId: 'evently-app-b92e5',
    authDomain: 'evently-app-b92e5.firebaseapp.com',
    storageBucket: 'evently-app-b92e5.firebasestorage.app',
    measurementId: 'G-JKS0S61NPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8w7JK31nOb7gYj5SbptMdgcG_LxX8ExA',
    appId: '1:7485850405:android:af2a73f9dd22b01c27d0cc',
    messagingSenderId: '7485850405',
    projectId: 'evently-app-b92e5',
    storageBucket: 'evently-app-b92e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWp6XW4uknUjBP6isQNRWgdAQ1FzhifSc',
    appId: '1:7485850405:ios:ccef7d4393e3b7e227d0cc',
    messagingSenderId: '7485850405',
    projectId: 'evently-app-b92e5',
    storageBucket: 'evently-app-b92e5.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWp6XW4uknUjBP6isQNRWgdAQ1FzhifSc',
    appId: '1:7485850405:ios:ccef7d4393e3b7e227d0cc',
    messagingSenderId: '7485850405',
    projectId: 'evently-app-b92e5',
    storageBucket: 'evently-app-b92e5.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUEr1vknC5jou9fBsXEbxpfCHS6hQx3Qo',
    appId: '1:7485850405:web:22cea9e414e56cc127d0cc',
    messagingSenderId: '7485850405',
    projectId: 'evently-app-b92e5',
    authDomain: 'evently-app-b92e5.firebaseapp.com',
    storageBucket: 'evently-app-b92e5.firebasestorage.app',
    measurementId: 'G-TEHYTKCZEM',
  );

}